=head1 NAME

SpreadButtler - A System providing access to a spreadsheet from within a webpage

=head1 SYSTEM DESCRIPTION

SpreadButtler consists of two  components. 

=over

=item *

A Mojolicious server side application, able read an excel spread sheet and
offering a rest interface to access its content.

=item *

A jQuery javascript plugin that requests data from from the server and
inserts the data into a suitably prepared html table object.

=back

=head1 AUTHOR

Tobi Oetiker E<lt>tobi@oetiker.chE<gt>

=head1 HISTORY

 2011-08-31 Initial Version

